### ISSUE TITLE
find a typo or other mistake on the class website

### ISSUE THREAD

**Issue by maxheld83** [soztag/fossos#11]
- [ ] post it as a *separate* issue
- [ ] reference it from this issue

**Comment by Elen93** [comment]
Found a spelling error!
See #54.

**Comment by DomBert** [comment]
I found a little little mistake in the indication of the software **Homebrew**. #61

**Comment by KonsWeb** [comment]
I found a slight oversight, see #63.

**Comment by maxheld83** [comment]
seems like you guys caught all of the typos etc. so I'm going to close this now.
