### ISSUE TITLE
fix startup warning messages

### ISSUE THREAD

**Issue by maxheld83** [soztag/fossos#113]

**Comment by maxheld83** [comment]
@samshaffer97 can copy paste the error messages?

**Comment by samshaffer97** [comment]
During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_COLLATE failed, using "C" 
3: Setting LC_TIME failed, using "C" 
4: Setting LC_MESSAGES failed, using "C" 
5: Setting LC_MONETARY failed, using "C" 
Error in yaml::yaml.load(string, ...) : 
  Scanner error: while scanning a simple key at line 4, column 1 could not find expected ':' at line 5, column 1

**Comment by maxheld83** [comment]
@samshaffer97 does [the fix documented here](https://stackoverflow.com/questions/9689104/installing-r-on-mac-warning-messages-setting-lc-ctype-failed-using-c) solve it for you?
Worked for me.

**Comment by maxheld83** [comment]
btw, I think this is an issue that only affects macOS users.

**Comment by samshaffer97** [comment]
yes it worked :)
