### ISSUE TITLE
suggest improvements to the class website

### ISSUE THREAD

**Issue by maxheld83** [soztag/fossos#12]
- [ ] find a section on the class website that you find confusion
- [ ] reference it in a *new* issue; make a suggestion for improving the class website
- [ ] point to that new issue here

**Comment by maxheld83** [comment]
I raised an issue over in https://github.com/maxheld83/fossos/issues/48

**Comment by t-rop** [comment]
I've created an issue regarding privacy in #50

**Comment by Mococoa22** [comment]
I have made an issue about colors in #53.

**Comment by Elen93** [comment]
I´ve made an issue in #55.

**Comment by DomBert** [comment]
I wrote some ideas about **logo implementation** of software in #62 .

**Comment by KonsWeb** [comment]
I've suggested a minor change in #64 .

**Comment by AndreM92** [comment]
I have made an issue about the hyperlinks in #68

**Comment by Ch1pzZz** [comment]
I have raised an issue about the website in #71
