### ISSUE TITLE
chocolatey cannot upgrade, "access denied"

### ISSUE THREAD

**Issue by maxheld83** [soztag/fossos#124]
@mkkkt can you add the chocolatey error message here?

**Comment by maxheld83** [comment]
@mkkkt can you run the command as per https://chocolatey.org/docs/troubleshooting#access-to-the-path-is-denied and see whether that fixes the problem?

**Comment by mkkkt** [comment]
$ choco upgrade all
Chocolatey v0.10.11
Chocolatey detected you are not running from an elevated command shell
 (cmd/powershell).

 You may experience errors - many functions/packages
 require admin rights. Only advanced users should run choco w/out an
 elevated shell. When you open the command shell, you should ensure
 that you do so with "Run as Administrator" selected. If you are
 attempting to use Chocolatey in a non-administrator setting, you
 must select a different location other than the default install
 location. See
 https://chocolatey.org/install#non-administrative-install for details.


 Do you want to continue?([Y]es/[N]o): y

Upgrading the following packages:
all
By upgrading you accept licenses for the packages.
chocolatey v0.10.11 is the latest version available based on your source(s).
chocolatey-core.extension v1.3.3 is the latest version available based on your source(s).

You have pandoc v2.3.1 installed. Version 2.5 is available based on your source(s).
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 パス 'C:\ProgramData\chocolatey\lib-bkp' へのアクセスが拒否されました。
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 パス 'C:\ProgramData\chocolatey\lib-bkp' へのアクセスが拒否されました。
Maximum tries of 3 reached. Throwing error.
Cannot create directory "C:\ProgramData\chocolatey\lib-bkp". Error was:
System.UnauthorizedAccessException: パス 'C:\ProgramData\chocolatey\lib-bkp' へのアクセスが拒否されました。
   場所 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   場所 System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   場所 System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   場所 chocolatey.infrastructure.filesystem.DotNetFileSystem.<>c__DisplayClass64.<create_directory>b__63()
   場所 chocolatey.infrastructure.tolerance.FaultTolerance.<>c__DisplayClass1.<retry>b__0()
   場所 chocolatey.infrastructure.tolerance.FaultTolerance.retry[T](Int32 numberOfTries, Func`1 function, Int32 waitDurationMilliseconds, Int32 increaseRetryByMilliseconds, Boolean isSilent)
   場所 chocolatey.infrastructure.filesystem.DotNetFileSystem.create_directory(String directoryPath)
   場所 chocolatey.infrastructure.filesystem.DotNetFileSystem.create_directory_if_not_exists(String directoryPath, Boolean ignoreError)
pandoc not upgraded. An error occurred during installation:
 パス 'C:\ProgramData\chocolatey\lib-bkp' へのアクセスが拒否されました。
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 パス 'C:\ProgramData\chocolatey\lib\pandoc\.chocolateyPending' へのアクセスが拒否されました。
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 パス 'C:\ProgramData\chocolatey\lib\pandoc\.chocolateyPending' へのアクセスが拒否されました。
Maximum tries of 3 reached. Throwing error.
パス 'C:\ProgramData\chocolatey\lib\pandoc\.chocolateyPending' へのアクセスが拒否されました。

**Comment by mkkkt** [comment]
It worked well, thank you.
