### ISSUE TITLE
document rmarkdown conversion chain

### ISSUE THREAD

**Issue by maxheld83** [soztag/fossos#127]
The document conversion chain (all the way from rmarkdown to pdf or whatever) is *really* complicated and can be quite confusing.
Normally `rmarkdown::render_site()` (and friends) does all of these steps for us, but it's important to be able to debug the individual components of this chain.

So it'd be great to:

- [ ] link to a couple of resources on the website that explain this chain,
- [ ] create and/or include existing visualisations that help people grasph this chain.

I'm going to include some links that I came across below, and everyone else should feel welcome to do the same.

If you're interested in "solving" this (for credit!) please assign yourself.

**Comment by maxheld83** [comment]
- http://www.geo.uzh.ch/microsite/reproducible_research/post/rr-r-publication/
- https://rmarkdown.rstudio.com/authoring_quick_tour.html
- https://sachsmc.github.io/knit-git-markr-guide/knitr/knit.html
- https://stackoverflow.com/questions/40563479/relationship-between-r-markdown-knitr-pandoc-and-bookdown

As always, there may not be a need to reinvent the wheel; there's already so much stuff out there.

**Comment by t-rop** [comment]
I found this (german) hands-on guide also helpful for understanding the workflow: 
- https://vijual.de/2018/11/07/artikel-mit-markdown-und-pandoc-schreiben/

As @maxheld83 indicated,  rmarkdown::render() consists of multiple steps.
Here's what is happening to the example file "example.Rmd" if we execute rmarkdown::render("example.Rmd") :

1. using knitr, the R code within "example.Rmd" will be executed. The results will be written to another file named "example.md"
2. using pandoc, "example.Rmd" or respectively "example.md" will be converted to the specified file format. By default, the output is a .HTML file. So, as per the example, a file named "example.html" will be generated.

Executing rmarkdown::render_site() will render all *.Rmd and *.md files of the current directory to HTML format. 
The exception: *.Rmd Files beginning with _ are excluded by default.

Additional resources:
The official documentations of [knitr](https://www.rforge.net/doc/packages/knitr/knit.html) and [pandoc](http://pandoc.org/getting-started.html) are also well written. They usually provide helpful insight as well.

**Comment by t-rop** [comment]
This visualization is from one of the class courses. It also makes clear that pandoc is the responsible tool for the output file format.
![conversion_chain](https://user-images.githubusercontent.com/44171964/54091252-45f2ef80-437e-11e9-8ab2-9b58308e139e.png)

**Comment by maxheld83** [comment]
thanks for adding these good resources here @t-rop – I think you already did plenty of work in our other branches, so I'm going to leave this one open in case someone else in future wants to build off of your starting points here and write something about it.
