### ISSUE TITLE
sign up to rstudio cloud and report back here

### ISSUE THREAD

**Issue by maxheld83** [soztag/fossos#14]

**Comment by Mococoa22** [comment]
my user name is [moco-t](https://rstudio.cloud/profile)

**Comment by mkkkt** [comment]
my user name is mkkkt.

**Comment by KonsWeb** [comment]
My user name is Kons Web.

**Comment by DomBert** [comment]
https://rstudio.cloud/profile

My account name is **dombert**, but you can find me with my full name: Dominik Bertram.

**Comment by t-rop** [comment]
Do we need rStudio Cloud account even if we use the local setup?

**Comment by maxheld83** [comment]
nope, this is optional @t-rop. If you're confident in your local setup, there's absolutely no need for rstudio.cloud. 
I just wanted this as a backstop, in case people can't get their environments to work.

**Comment by Elen93** [comment]
This is my profile  https://community.rstudio.com. My account name is Elen93!

**Comment by AndreM92** [comment]
My username is Andre M92

**Comment by samshaffer97** [comment]
my username is samshaffer97

**Comment by Ch1pzZz** [comment]
My username is Ch1pzZz
