### ISSUE TITLE
Incompatible macOS Version for Docker

### ISSUE THREAD

**Issue by DomBert** [soztag/fossos#145]
**Fatal Error**

Docker requires macOS version 10.12.0 or higher. As I checked it up, my hardware isn't capable for more. 

Any suggestions? 

![image](https://user-images.githubusercontent.com/44197630/56722809-19394280-6748-11e9-88db-4a0d66138367.png)

**Comment by Crisphi** [comment]
https://docs.docker.com/toolbox/toolbox_install_mac/ 
Have a look at this instruction. 
I had the same problem with Windows 10 home. You have to install the Docker Toolbox instead of Docker Desktop. Docker will then run in a virtual machine.

**Comment by DomBert** [comment]
@Crisphi Great! Totally worked. 
![image](https://user-images.githubusercontent.com/44197630/56796296-87e2d280-6812-11e9-8c97-774e671a0c6a.png)

**Comment by maxheld83** [comment]
thanks for troubleshooting this @Crisphi.
I'm going to close this because it's probably a fairly rare problem.

@DomBert I'm afraid a macOS < 10.12. may also cause problems with other CLI software, but once you get docker to work at least everything *inside* it should work.
