### ISSUE TITLE
find an interesting discussion on RStudio community

### ISSUE THREAD

**Issue by maxheld83** [soztag/fossos#15]
- [ ] post it here
- [ ] explain why it is interesting

**Comment by Mococoa22** [comment]
1. [discussion of shiny](https://community.rstudio.com/t/discussion-when-is-shiny-a-good-choice-vs-when-is-it-not-the-right-tool-for-the-job/707/8)

2. it was interesting that I could learn the advantages and disadvantages about shiny although I have never used shiny before by sharing  people their own experience.

**Comment by DomBert** [comment]
1. https://community.rstudio.com/t/how-to-find-the-corresponding-grid-centroids/16718
2. i don't really understand what they are talking about. but i do really like the fact, people discussing about geoinformational problems with grids in this community.

**Comment by maxheld83** [comment]
hehe, I have no idea what this is about either @DomBert but good to know that GIS topics are also active in the #rstats community.

**Comment by mkkkt** [comment]
[about teaching R](https://community.rstudio.com/t/i-guess-thats-why-they-call-it-the-teaching-blues/2710)
This thread show us that there are many students who think it is difficult to learn computer programingskills like R. But reading this thread, I can see also  R is really useful if I can make full use of it. This thread encourage me.

**Comment by t-rop** [comment]
https://community.rstudio.com/t/rstudio-hidden-gems/4974
this is about great rstudio functions that are a little hidden / unknown to many people. I've skimmed through them and it looked very helpful and interesting

**Comment by maxheld83** [comment]
this is so cool, thanks for unearthing this @t-rop  – I wasn't aware of many of these shortcuts.
Many of those are also covered in `Help > Keyboard Shortcuts Help`, but not all of them.

These kinds of shortcuts may sound a little trivial for beginners, but I really recommend sitting down and forcing yourself to learn as many as possible. (It helps to just put away the mouse).
It's amazing how much faster you become with just the keyboard.
And once its in your muscle memory, you *really* become so much more efficient.

This is also why it makes sense to commit to *one* IDE/editor and really learn it deeply. It pays off.

**Comment by Elen93** [comment]
1. https://community.rstudio.com/t/what-are-your-recommendations-for-thesis-writing-with-rstudio-and-rmarkdown/13576
2. For future reference. I want to learn to use rmarkdown and rstudio for my academic writing.

**Comment by maxheld83** [comment]
I can really recommend RMarkdown for academic writing @Elen93  – takes some time initially, but then pays off big time. Results look great, and, what is more important – the tech forces you to think about content, not formatting.
We'll talk more about this in class 🍾

**Comment by samshaffer97** [comment]
1. https://community.rstudio.com/t/merge-two-dataframes/16652/5
2. i don't entirely understand what the solution to this problem but i think this could be useful once undestood
