### ISSUE TITLE
install bash shell and report back with screenshot here

### ISSUE THREAD

**Issue by maxheld83** [soztag/fossos#17]

**Comment by Mococoa22** [comment]
Thank you @maxheld83 for helping.

![terminal bash screenshot](https://user-images.githubusercontent.com/44197609/47180830-633a0980-d35c-11e8-9d4c-3cfb4e222602.png)

**Comment by mkkkt** [comment]
![image](https://user-images.githubusercontent.com/44181318/47272411-384fef80-d5c0-11e8-9144-95049f8a4cab.png)

**Comment by KonsWeb** [comment]
![screen9](https://user-images.githubusercontent.com/44196947/47306950-0bd2bc80-d62e-11e8-8235-82e439e45132.png)

**Comment by DomBert** [comment]
![image](https://user-images.githubusercontent.com/44197630/47412801-f3b58700-d76c-11e8-9381-5422d4686d8f.png)

**Comment by t-rop** [comment]
![image](https://user-images.githubusercontent.com/44171964/47563700-ed690b80-d922-11e8-9ba3-40d419b88c3b.png)
Using the Windows Subsystem for Linux. Thanks again for the suggestion @maxheld83

**Comment by Elen93** [comment]
![screenshot 3](https://user-images.githubusercontent.com/40487564/47568910-9a975000-d932-11e8-98b5-da72b249bc1a.png)

**Comment by AndreM92** [comment]
![bash shell](https://user-images.githubusercontent.com/44435994/47609275-c7835a00-da3b-11e8-8bfd-077a6295f5b8.jpg)

**Comment by spaniel19** [comment]
I assume this is correct!

![capture](https://user-images.githubusercontent.com/44197419/47621276-af701100-daf5-11e8-973d-f93900f1cba9.PNG)

**Comment by MoPau** [comment]
![30 10](https://user-images.githubusercontent.com/44197606/47715786-1bab5b80-dc41-11e8-8c3b-1b8a278bcb36.JPG)
