### ISSUE TITLE
Query Wikidata programmatically with R for the Nuremberg Time Machine Project

### ISSUE THREAD

**Issue by Crisphi** [soztag/fossos#178]
For the Nuremberg Time Machine Project we want to find all pictorial representations (and subclasses of it) that have a connection to Nuremberg. 
It could be helpful to split the query programmatically into smaller ones, going recursively through the data, because of the size of the dataset, the depth of the query and the structure of the database.

**Comment by Crisphi** [comment]
![IMG_20191101_142945](https://user-images.githubusercontent.com/49362063/68039751-1312b880-fccd-11e9-9403-e2b098fcc407.jpg)
Latest Version of the mindmap I created to get a better overview. 

The project turns out to be more difficult than expected. 
I have to do some more concept work before writing some code in R to solve this Problem. 
Because of that the Issue can be (at least temporarily) closed.

**Comment by maxheld83** [comment]
not sure this still relevant, but I just (weird coincidence) ran into these tweets/project for querying WikiData from rstats:

- https://masalmon.eu/2017/08/06/p1/
- https://cran.r-project.org/web/packages/WikidataR/index.html (I think you used this already?)
- https://people.wikimedia.org/~bearloga/notes/r-pkgs.html
- https://masalmon.eu/2017/08/06/p1/
- https://github.com/statistikZH/SPARQL_WITH_R

I'm guessing that the fundamental limitations (compute time for deep queries) that you identified still apply, but it might be worth reaching out to the people who were working on this to see what their thoughts are.
