### ISSUE TITLE
install package manager and report back with screenshot here

### ISSUE THREAD

**Issue by maxheld83** [soztag/fossos#18]

**Comment by Mococoa22** [comment]
I hope this is correct.
I installed homebrew.
Does download takes some time? 
It's been downloading for 10min. and it's still doing it so I'm worried.

![terminal homebrew installed screenshot](https://user-images.githubusercontent.com/44197609/47182634-df365080-d360-11e8-97b2-50b5409969fc.png)

**Comment by t-rop** [comment]
![image](https://user-images.githubusercontent.com/44171964/47530276-6d06c400-d8aa-11e8-964d-8838de5e421b.png)

**Comment by Elen93** [comment]
![screenshot 8](https://user-images.githubusercontent.com/40487564/47577155-83faf400-d946-11e8-9787-17236608e2ef.png)

**Comment by AndreM92** [comment]
![chocolatey](https://user-images.githubusercontent.com/44435994/47617344-99972780-dac6-11e8-8f55-8f472cf3ea00.jpg)
I have installed Chocolatey.

**Comment by spaniel19** [comment]
![capture4](https://user-images.githubusercontent.com/44197419/47710100-31655480-dc32-11e8-8453-055f11582964.PNG)

**Comment by maxheld83** [comment]
to all who have Windows Subsystem for Linux available and have chosen Ubuntu as a Linux Distro, you should also have `apt-get` as a package manager available for the WSL.
