### ISSUE TITLE
install atom text editor with packages and report back with screenshot here

### ISSUE THREAD

**Issue by maxheld83** [soztag/fossos#19]

**Comment by Mococoa22** [comment]
![atom installed with packages](https://user-images.githubusercontent.com/44197609/47209230-c95d7580-d3ca-11e8-83ed-919f10bade2b.png)

**Comment by mkkkt** [comment]
![image](https://user-images.githubusercontent.com/44181318/47273010-80731000-d5c8-11e8-8015-1d7e071f9626.png)

**Comment by KonsWeb** [comment]
![screen3](https://user-images.githubusercontent.com/44196947/47306735-8b13c080-d62d-11e8-8053-7abbbcbe3aa9.png)

**Comment by DomBert** [comment]
![image](https://user-images.githubusercontent.com/44197630/47414437-3ed19900-d771-11e8-8336-c04223bb65b8.png)

**Comment by t-rop** [comment]
![image](https://user-images.githubusercontent.com/44171964/47530056-da662500-d8a9-11e8-98b3-2f91c542768c.png)

**Comment by Ch1pzZz** [comment]
![snip_atomtext](https://user-images.githubusercontent.com/44197143/47706920-b6e50680-dc2a-11e8-9632-4f52437271af.PNG)

**Comment by spaniel19** [comment]
![capture6](https://user-images.githubusercontent.com/44197419/47711262-1cd68b80-dc35-11e8-813c-b756c9016deb.PNG)
