### ISSUE TITLE
install git scm and report back here with screenshot

### ISSUE THREAD

**Issue by maxheld83** [soztag/fossos#21]

**Comment by Mococoa22** [comment]
![git installed screenshot](https://user-images.githubusercontent.com/44197609/47224862-92518900-d3f7-11e8-9aeb-7db91274b0c3.png)

**Comment by KonsWeb** [comment]
![screen4](https://user-images.githubusercontent.com/44196947/47306674-67e91100-d62d-11e8-9eec-6e1b13e5b7b1.png)

**Comment by DomBert** [comment]
Installed the GitHub Desktop App.

![image](https://user-images.githubusercontent.com/44197630/47414901-6e34d580-d772-11e8-8e05-b74305beec64.png)

**Comment by maxheld83** [comment]
thanks @DomBert! *This* issue was actually about the git CLI (just the command line tool). The GitHub Desktop GUI is in #22.
But, no matter, I am guessing that if GitHub Desktop works, then it *has* git cli under the hood. So no problem.

**Comment by t-rop** [comment]
![image](https://user-images.githubusercontent.com/44171964/47531091-db4c8600-d8ac-11e8-9b0a-3bb30b62aafd.png)
does it make sense to use the GUI version instead of CLI?

**Comment by maxheld83** [comment]
hehe, that's pretty controversial @t-rop 🤷‍♂️.
Using the CLI is, in some ways, safer, because it exposes you directly to git, and you'll have access to all the bells and whistles – but, there's no training wheels.
Using the GUI gives you a great interface and lots of training wheels, but it's actually *easier* to bork things up with the GUI, I think. 

For harder problems, there's often no way around the CLI, so you end up having to go back to the CLI anyway.

On the other hand, the GUI has build-in diffing, and there's really no great way to diff on the CLI.

We'll talk about this more in class. At the end of the day, people should decide for themselves.

**Comment by Elen93** [comment]
![screenshot 10](https://user-images.githubusercontent.com/40487564/47577915-59aa3600-d948-11e8-9fdd-7496b78297d6.png)

**Comment by AndreM92** [comment]
![git](https://user-images.githubusercontent.com/44435994/47609364-4200a980-da3d-11e8-88ad-5ffee4f8fd87.jpg)

**Comment by Ch1pzZz** [comment]
![snip_gitscm](https://user-images.githubusercontent.com/44197143/47706706-38886480-dc2a-11e8-8194-c637e5be6704.PNG)

**Comment by spaniel19** [comment]
![capture8](https://user-images.githubusercontent.com/44197419/47722660-35ee3500-dc53-11e8-9e4a-0d4723008968.PNG)
