### ISSUE TITLE
install github desktop and report back here with a screenshot

### ISSUE THREAD

**Issue by maxheld83** [soztag/fossos#22]

**Comment by Mococoa22** [comment]
![github desktop](https://user-images.githubusercontent.com/44197609/47224934-c0cf6400-d3f7-11e8-824f-d0d17f5007b0.png)

**Comment by mkkkt** [comment]
![image](https://user-images.githubusercontent.com/44181318/47272456-ff644a80-d5c0-11e8-948a-3ed363501585.png)

**Comment by KonsWeb** [comment]
![screen5](https://user-images.githubusercontent.com/44196947/47306465-d4afdb80-d62c-11e8-9bb0-b2409d71a8ae.png)

**Comment by Elen93** [comment]
![screenshot 6](https://user-images.githubusercontent.com/40487564/47575218-d554b480-d941-11e8-8669-98de3ab9fd5b.png)

**Comment by Ch1pzZz** [comment]
![snip_github desktop](https://user-images.githubusercontent.com/44197143/47706441-72a53680-dc29-11e8-880b-3997408fe869.PNG)

**Comment by spaniel19** [comment]
![capture9](https://user-images.githubusercontent.com/44197419/47722929-c0369900-dc53-11e8-8176-9d620a313518.PNG)
