### ISSUE TITLE
install pandoc and report back here with a screenshot

### ISSUE THREAD

**Issue by maxheld83** [soztag/fossos#23]
this might need a package manager first!

**Comment by mkkkt** [comment]
![image](https://user-images.githubusercontent.com/44181318/47270687-6cb8b100-d5aa-11e8-9bcb-f5f092adb154.png)

**Comment by KonsWeb** [comment]
![screen7](https://user-images.githubusercontent.com/44196947/47306390-90bcd680-d62c-11e8-9e80-5ce7e5e6b075.png)

**Comment by t-rop** [comment]
![image](https://user-images.githubusercontent.com/44171964/47531759-ccff6980-d8ae-11e8-9980-175ba8e9fa16.png)

**Comment by Elen93** [comment]
![screenshot 9](https://user-images.githubusercontent.com/40487564/47577644-b5c08a80-d947-11e8-92c3-3f5cdde9f571.png)

**Comment by AndreM92** [comment]
![pandoc](https://user-images.githubusercontent.com/44435994/47622275-9f5f2e00-db03-11e8-8765-2bd5e8a2bfea.jpg)

**Comment by spaniel19** [comment]
![capture7](https://user-images.githubusercontent.com/44197419/47713292-3cbc7e00-dc3a-11e8-8706-c2b061523058.PNG)
