### ISSUE TITLE
install latex and report back here with a screenshopt

### ISSUE THREAD

**Issue by maxheld83** [soztag/fossos#24]

**Comment by Mococoa22** [comment]
![latex installed screenshot](https://user-images.githubusercontent.com/44197609/47254836-2546fd80-d4a2-11e8-8038-db241dfe7105.png)

**Comment by mkkkt** [comment]
![image](https://user-images.githubusercontent.com/44181318/47272248-d1313b80-d5bd-11e8-9b67-5d09d558dd71.png)

**Comment by DomBert** [comment]
![image](https://user-images.githubusercontent.com/44197630/47604169-0989ad00-d9f6-11e8-88f2-7cf8cac1e5a0.png)

**Comment by AndreM92** [comment]
![miktex](https://user-images.githubusercontent.com/44435994/47618108-686f2500-dacf-11e8-9653-58e17aea44de.jpg)

**Comment by Ch1pzZz** [comment]
![snip_miktex](https://user-images.githubusercontent.com/44197143/47705756-cca4fc80-dc27-11e8-8dec-34bf46ee699f.PNG)

**Comment by spaniel19** [comment]
![capture3](https://user-images.githubusercontent.com/44197419/47708647-cbc39900-dc2e-11e8-9b89-5f3cd8145fa8.PNG)

**Comment by spaniel19** [comment]
Is Texmaker fine too?

**Comment by maxheld83** [comment]
sure @spaniel19, TexMaker is just a GUI and will use the same LaTeX-CLI under the hood.

Incidentally, [LyX](https://www.lyx.org) is the LaTeX-Wysiwyg Editor I mentioned; I don't recommend it though.
