### ISSUE TITLE
install pandoc citeproc and report back here with a screenshot

### ISSUE THREAD

**Issue by maxheld83** [soztag/fossos#25]

**Comment by Mococoa22** [comment]
![pandoc citeproc installed screenshot](https://user-images.githubusercontent.com/44197609/47254499-6e954e00-d49e-11e8-9ac0-c76f97f4b550.png)

**Comment by mkkkt** [comment]
I'm not sure if I can ask a question here. But It would be appreciated if someone tell me how to install pandoc-citeproc. I could install pandoc.

**Comment by spaniel19** [comment]
I am also installing Pandoc, also not sure how to install citeproc!
