### ISSUE TITLE
install or describe your chosen bibliography manager and report with screenshot here

### ISSUE THREAD

**Issue by maxheld83** [soztag/fossos#26]

**Comment by Mococoa22** [comment]
Mendeley

![mendeley desktop installed screenshot](https://user-images.githubusercontent.com/44197609/47256588-c8594080-d4bd-11e8-96f1-d10d090a2c22.png)

**Comment by KonsWeb** [comment]
I usually work with Citavi:
![screen6](https://user-images.githubusercontent.com/44196947/47306033-949c2900-d62b-11e8-9c19-6b2cb921b55c.png)

**Comment by DomBert** [comment]
Mendeley.
![image](https://user-images.githubusercontent.com/44197630/47308798-f613c600-d632-11e8-80b5-61dd5023a45f.png)

**Comment by Ch1pzZz** [comment]
![snip citavi](https://user-images.githubusercontent.com/44197143/47344670-55142200-d6a9-11e8-8db8-47ee498c8b6f.PNG)

Using Citavi as well

**Comment by spaniel19** [comment]
Here we go...

![screenshot 3](https://user-images.githubusercontent.com/44197419/47349838-c5747080-d6b4-11e8-8e7a-2ef9530366db.png)

**Comment by Elen93** [comment]
![screenshot 12](https://user-images.githubusercontent.com/40487564/47581004-9ed26600-d950-11e8-9748-652f6e1244ea.png)
Mendeley!!!

**Comment by AndreM92** [comment]
![citavi](https://user-images.githubusercontent.com/44435994/47622467-64f69080-db05-11e8-9f20-f2a9a91b0048.jpg)

**Comment by AndreM92** [comment]
![citavi](https://user-images.githubusercontent.com/44435994/47622484-9e2f0080-db05-11e8-8a11-090efd7ca65e.jpg)

**Comment by maxheld83** [comment]
gosh, I wish Citavi was available on macOS/Linux and open source ... I hear so many good things about it (mainly that it also works great as an outliner, not just a reference manager)
