### ISSUE TITLE
install the tidyverse packages and report back with a screenshot here

### ISSUE THREAD

**Issue by maxheld83** [soztag/fossos#28]

**Comment by Mococoa22** [comment]
![tidy verse installed screenshot](https://user-images.githubusercontent.com/44197609/47254880-ab634400-d4a2-11e8-93c7-b661d8e01224.png)

**Comment by maxheld83** [comment]
@Mococoa22 it might help if you install the missing packages by hand, then reinstall tidyverse.

```
install.packages(c("httr","rvest"))
install.packages("tidyverse")
```

If the problem persists, please open a new issue and we'll fix it in class.

**Comment by Mococoa22** [comment]
I could installed the first 

> install.packages(c("httr","rvest"))

but the next one i tried to reinstall again and I guess it failed 

![tidyverse problem](https://user-images.githubusercontent.com/44197609/47256484-4ae10080-d4bc-11e8-8216-4ead9e8621ae.png)

**Comment by t-rop** [comment]
![image](https://user-images.githubusercontent.com/44171964/47564176-69178800-d924-11e8-897e-a8193d3c6f75.png)
Done :)

**Comment by DomBert** [comment]
**Got it.**

![image](https://user-images.githubusercontent.com/44197630/47614071-f3352d00-da99-11e8-9af2-e32d3084b24f.png)


![image](https://user-images.githubusercontent.com/44197630/47614059-d6005e80-da99-11e8-8ebb-62aa112feeb8.png)

**Comment by Ch1pzZz** [comment]
![snip_tidyverse](https://user-images.githubusercontent.com/44197143/47616740-2ccd5e80-dac1-11e8-8918-4f103626f9e0.PNG)

**Comment by KonsWeb** [comment]
![screen11](https://user-images.githubusercontent.com/44196947/47667242-ca9a5980-dba5-11e8-8268-47c12c5d8fd6.png)
