### ISSUE TITLE
describe your chosen operating system

### ISSUE THREAD

**Issue by maxheld83** [soztag/fossos#30]
- [ ] macOS, Linux or Windows
- [ ] Version

**Comment by t-rop** [comment]
I'm using Windows 10 with the latest October 2018 update.
In parallel, I'm trying to familiarize myself with some Linux distributions. But so far, I'm still not used to these...

**Comment by maxheld83** [comment]
cool @t-rop – any luck with running a linux distro *inside* windows via this newfangled [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) or some hypervisor magic? I don't really know anything about Windows, but I've heard good things about running Linux inside Windows even *without* full virtualisation or dual-boot.

For everyone else, I summarised the choices and links here: https://www.maxheld.de/fossos/stack.html#moving_to_linux

**Comment by DomBert** [comment]
I'm using macOS. It's a MacBook 5,1 with the OS X 10.11.6 version.

**Comment by t-rop** [comment]
@maxheld83 I've read about the subsystem a few month ago, but didn't try it out. Yesterday, i changed that and installed it. Seems to work fine, however it is limited to command line stuff.
So might be useful for some, but i dont think it'll help much in this course.

Installed Debian on an external drive, which I'll maybe use for this course (and similar ones).

**Comment by Elen93** [comment]
I'm also using Windows 10 with the latest update!!

**Comment by samshaffer97** [comment]
I'm using macOS on a Macbook Air, with the OS X 10.13.6 version

**Comment by KonsWeb** [comment]
At home, I am working with the latest Windows 10 version. My laptop, however, is a little older and only runs on Windows 7 (I intend to get a new one in the next few months).

**Comment by maxheld83** [comment]
great, thanks everyone (so far).
You all seem to have pretty new*ish*, powerful machines.
Lest anyone get the wrong idea, I just wanted to highlight that you can also participate (just as well) in this class with an old, dirt-cheap laptop (ideally with Linux). See https://www.maxheld.de/fossos/#hardware_requirements for details.

**Comment by Ch1pzZz** [comment]
Hi I´m also using Windows 10 at home. Will have to use 8 on my Laptop.

**Comment by spaniel19** [comment]
Good morning! I am also using windows 10!

**Comment by maxheld83** [comment]
seems like a broad mix, I'm going to close this now.
