### ISSUE TITLE
study section on literate programming

### ISSUE THREAD

**Issue by maxheld83** [soztag/fossos#39]
https://www.maxheld.de/fossos/stack.html#literate_programming

You'll find a lot of stuff in the listed resources that pertain to using R *inside* documents.
That's not our focus for now, and you can skip that.

Concentrate on the parts *without* R.

**Comment by VerenaKasztantowicz** [comment]
Unfortunately the link seems to be broken. Could you point me to the resources, @maxheld83? I just wanted to add some material.

**Comment by maxheld83** [comment]
the resources are now at https://soztag.github.io/fossos/
