### ISSUE TITLE
get consent for audio recording

### ISSUE THREAD

**Issue by maxheld83** [soztag/fossos#49]
this was a request by @Mococoa22

**Comment by maxheld83** [comment]
I have no issue with this; we'll ask everyone at the beginning of the next seminar. If there are no objections, that's fine by me.

I should note that I expect there will be hardly any "lecture-type" instruction, we'll mostly be working in small groups or just individually.

**Comment by DomBert** [comment]
For me that's fine, as well.

**Comment by maxheld83** [comment]
not having heard anything otherwise, I'm going to say you're good to go @Mococoa22 !
