### ISSUE TITLE
streamline FAU Affiliation: "Friedrich-Alexander Universität Erlangen-Nürnberg (FAU)"

### ISSUE THREAD

**Issue by t-rop** [soztag/fossos#51]
On the class website, FAU is referenced as "Friedrich-Alexander Universität Erlangen-Nürnberg (FAU)". 
The correct way would be an added hyphen so it looks like "Friedrich-Alexander-Universität Erlangen-Nürnberg (FAU)" as can be found [here](https://www.fau.de/intranet/corporate-identity/leitfaden-affiliation-deutsch-und-englisch/).

**Comment by maxheld83** [comment]
yikes, I can never get this right.
Thanks for spotting this mistake @t-rop.
I'm going to leave the issue open, just so someone in class can be the one to fix this later in the semester, once we've covered git.
So we'll just put this on hold for session 4 or so.

(Of course I'll always fix urgent issues such as the privacy concern you raised in #50 right away).
