### ISSUE TITLE
Uncoloring a paragraph in 'Expectations'

### ISSUE THREAD

**Issue by Mococoa22** [soztag/fossos#53]
In the **Expectations** part there is an orange box emphasizing what students should do before class. (You can see the syllabus from [here](https://www.maxheld.de/fossos/).)

But this color orange confuses where this box belongs to, whether to the '**Hardware Requirements**' or to the '**Expectations**',since it's the same color with the box above.

Though I am not yet sure what each color stands for,  I recommend that this orange box be in bold or underlined and not in colored box, because this part '**Expectations**' was originally not colored.

**Comment by maxheld83** [comment]
good point, we'll change this later, once we know how to!

**Comment by maxheld83** [comment]
the whole coloring thing is now in #59 so I'm going to close this as a duplicate.
