### ISSUE TITLE
fix typo: Indication of Homebrew as a software in capital letter

### ISSUE THREAD

**Issue by DomBert** [soztag/fossos#61]
In the Course Description the software **'Homebrew'** is mentioned. It is written in small letters. I for my part would write the Indication of a software with a capital letter at the beginning. There are some software written in small letters like *'bookdown'*, but in like I can see at the homepage it is *Homebrew*.

It's really hard to find some typos by the way ;)

**Comment by maxheld83** [comment]
glad it's hard to find them!
Thanks for spotting this inconsistency anyway!
I'm going to keep this open, so we can fix this in class once we know how to.
