### ISSUE TITLE
add logos and symbols to software in stack to aid navigation/orientation

### ISSUE THREAD

**Issue by DomBert** [soztag/fossos#62]
What I think, could improve the website on a didactical way, is to include some logos. For me, a bloody beginner, the mass of new software is absolutely overwhelming. In Fossos/**Stack** there is all the software mentioned, we can download. Right now, I can't really differ between them or nor keep them apart. 
To support the value of memory between the name and the function of the software, a overview with the logos could help, just to get to know them faster and get familiar with them.

**Comment by maxheld83** [comment]
that's a great idea.
Most of these pieces of software *have* logos, and many of them may be easily available via font-awesome or something.
Will keep this open, maybe we can get around to improving this ourselves.

**Comment by maxheld83** [comment]
the easiest way to implement this would be to use font-awesome symbols, if/to the extent they are available for the brands.
but even *without* the brands, one might use other, related font-awesome symbols.

This will require some html/css knowledge (not much).

**Comment by maxheld83** [comment]
this is extended in #84 to *also* use emojis for the same purpose.
This current issue would be easier to accomplish though.

If both issues are implemented, there should be some coordination between them.

**Comment by samshaffer97** [comment]
i have found logos for 
Atom (*https://fontawesome.com/icons/react?style=brands*) and 
gitHub (*https://fontawesome.com/icons/github?style=brands*)
i could not yet find any fitting logos for the rest on font-awesome, currently working on that

**Comment by samshaffer97** [comment]
Find fitting logos:

- [ ] GitHub/GitHub Desktop
- [ ] StackOverflow
- [ ] RStudio
- [ ] Git
- [ ] Homebrew
- [ ] Atom
- [ ] Pandoc
- [ ] LaTex

**Comment by maxheld83** [comment]
really cool @samshaffer97, I think this might help a lot of people better navigate the stack.
We also already have (some version of) font-awesome ready in our repository, though some of the more current symbols might need a more current font-awesome release, for which we might have to update the CSS and some other stuff that ships with font-awesome.

Just the *simple* icons (which already exist) might be a `pass/fail` kinda job, but expanding this to more icons including a newer font awesome release would be a `graded-1` job.

@samshaffer97 do you feel like taking over this issue? Of so, feel free to sign yourself up.

**Comment by maxheld83** [comment]
cool, thanks so much @samshaffer97 this worked beautifully!

**Comment by maxheld83** [comment]
and it's live! 🎆 🚢 

<img width="1034" alt="icons" src="https://user-images.githubusercontent.com/5372770/50970901-007f8680-14e3-11e9-9747-860b3ddbf0fe.png">
