### ISSUE TITLE
Removing an anacoluthon: Assessment

### ISSUE THREAD

**Issue by KonsWeb** [soztag/fossos#63]
In _Assessment_, the second sentence seems to lose its grammatical track halfway through: "Instead of some _make belief_ work or hobby project, we are, for the most part, assignments in this class are designed to be _actually useful_ to other people." I think that the intended formulation is: "Instead of some _make belief_ work or hobby project, assignments in this class are, for the most part, designed to be _actually useful_ to other people."

Also, a really nit-picky point: In the first sentence of _Expectations_, only the "lot"-part of "a lot" is italicized. I feel like the whole phrase is deserving of the empasis.

**Comment by maxheld83** [comment]
thanks for the careful copy-editing!
