### ISSUE TITLE
installing homebrew on old macOS

### ISSUE THREAD

**Issue by DomBert** [soztag/fossos#66]
I tried to install Homebrew with my Terminal. Unfortunately my system is too old. 
There are some alternatives installing this software presented on the website (https://docs.brew.sh/Installation), but I'm a overstrained right now. 
Could somebody help me?

![image](https://user-images.githubusercontent.com/44197630/47413231-07152200-d76e-11e8-93c6-eef0070d3e61.png)

**Comment by maxheld83** [comment]
thanks for bringing this up.
This could be a little thorny.

It actually *looks* like homebrew *did* install, it's just complaining a bit about the old macOS. Can you run `brew update` to confirm that homebrew is working?

Any chance you could update to a more recent version of macOS?
I'm afraid it's possible (though I don't know for sure) that other pieces of software also may not work, potentially in unexpected ways.

Is there any chance you could upgrade to a more recent version of macOS?

Homebrew, of course, is strictly speaking optional, so even if you can't get that to work, you may still be fine.
My hunch would be that probably most of the software *should* work, but I'm not sure.

**Comment by maxheld83** [comment]
incidentally, I think you also need to run `xcode-select --install` to install the dev tools on macOS. Does that still work on 10.11?

**Comment by maxheld83** [comment]
one more possible problem: can you install and run *current* Safari on (>= 12.0) on your mac? I think RStudio (at least up to 1.1.x) depends on current Safari, but I could be wrong.

**Comment by DomBert** [comment]
I tried to update my system to Mojave, but my hardware seems to be too old. So I'm gonna update to High Sierra tonight. Think that Homebrew should work afterwards.

**Comment by maxheld83** [comment]
I hope this has been solved @DomBert? Otherwise feel free to reopen.
