### ISSUE TITLE
add command line links

### ISSUE THREAD

**Issue by spaniel19** [soztag/fossos#69]
Hey!

I followed the instructions to install the bash shell on windows, but was at a loss when trying to do the tutorial on using the command line because I was located at /home and not at /mnt/c. 

Maybe I missed that info on the course page, but if it is not there, people with no background on this stuff may get confused. I found out how to do it on:

https://www.howtogeek.com/261383/how-to-access-your-ubuntu-bash-files-in-windows-and-your-windows-system-drive-in-bash/

Maybe one could add that info to the course page. 

All the best! 

P.S. Also, where the instructions to install the bash shell on windows are explained, there are two links to two webpages that explain how to it. Since the approaches are a bit different, that too may seem confusing to some.

**Comment by spaniel19** [comment]
I also found this visual first intro (https://www.youtube.com/watch?v=AO0jzD1hpXc) a bit more easy to follow than the explanation on directories here: http://www.vikingcodeschool.com/web-development-basics/a-command-line-crash-course.

**Comment by maxheld83** [comment]
great suggestions, will do.
