### ISSUE TITLE
sign up to github and say hi in this issue

### ISSUE THREAD

**Issue by maxheld83** [soztag/fossos#7]

**Comment by maxheld83** [comment]
Hi, I'm @maxheld83 I'm teaching this class.

**Comment by AndrewR25** [comment]
Hi, I am Andrii

**Comment by mkkkt** [comment]
I'm Makiko.

**Comment by t-rop** [comment]
Hi all, I'm Thomas.

**Comment by samshaffer97** [comment]
Hi, i'm Sam

**Comment by Elen93** [comment]
Hello, I´m Eleni!! My username is @Elen93!!!!

**Comment by Ch1pzZz** [comment]
Hi, I'm Fabi My username is @Ch1pzZz

**Comment by KonsWeb** [comment]
Hi, I'm Konstantin

**Comment by DomBert** [comment]
Hi, I'm Dominik!

**Comment by Mococoa22** [comment]
Hi I’m momoko

**Comment by spaniel19** [comment]
Hi, I'm Daniel! My username is @Spaniel19

**Comment by MoPau** [comment]
Hi, I´m Moritz. Nickname MoPau. Cheers

**Comment by maxheld83** [comment]
actually, I'm going to reopen this because a) not everyone has signed up yet and b) there's still a lot of empty profiles.

**Comment by maxheld83** [comment]
nice profile, thanks @AndreM92! And finally a profile with a picture of a person! Makes life *so* much easier ...

**Comment by aDeLe24** [comment]
Hello everyone, i'm Adèle.
