### ISSUE TITLE
install git with wsl

### ISSUE THREAD

**Issue by spaniel19** [soztag/fossos#70]
So Git is asking me a couple of install questions. I don't understand the implications.
I have installed the Windows Subsystem for Linux (WSL) and the Windows 10 Bash Shell. 
Insofar as this is possible, I would like to work with the Linux command line (not sure if that makes sense/ my vocab is correct).

Anyway, since I have installed the WSL, I am not sure what to click now. Normally I would just go for Windows default, but there are references to Unix etc. Not sure how this all interacts. The questions/options are: 
1. Path environment: Use Git from Git Bash only / Use Git from the Windows Command Prompt / Use Git and optional Unix tools from the Windows Command Prompt.
2. Choosing HTTPS transport backened: Use the OpenSSL library/ Use the native Windows Secure Channel library
3. Line ending conversions: Checkout Windows-style, commit Unix-style line endings/ Checkout as-is, commit Unix-style line endings/ Check out as-is, commit as-is
4. Configuring ternubak enulaot to use Git Bash: Use Min TTY (default terminal of MSYS2)/ Use Windows' default console window 

Unfortunately, this all sounds French to me. Anyone has any suggestions?

Thanks!

**Comment by spaniel19** [comment]
So the answer to the question: Ubuntu comes with Git, but I will install the windows version of Git anyway to install the windows Github-GIU over it anyway...

**Comment by maxheld83** [comment]
I am assuming this has been solved then.
