### ISSUE TITLE
programmatically document all contributors to the class website

### ISSUE THREAD

**Issue by maxheld83** [soztag/fossos#85]
Since a lot of people might end up contributing to this website (as per the issues), it would be nice to give credit to all those people (you guys!) *on* the website.

There should be a programmatic way to do this, as in programmatically reading in the contributions (accepted pull requests?) from github, and writing it out via R into the rmarkdown document.

I have seen this on other websites such as in Hadley's [advanced R](https://adv-r.hadley.nz/introduction.html#intro-ack) and that should give us some idea of how to accomplish this.

I'm pretty sure there is a good R package to access the github API, but I can't remember what it is called right now.

This would also have to run on Travis, so whenever we push to the repo, the list get updated.

**Comment by maxheld83** [comment]
maybe also check out `tidyverse::use_tidy_contributing()` https://usethis.r-lib.org/reference/tidyverse.html

**Comment by maxheld83** [comment]
@samshaffer97 just FYI, here's the paste example I just used – might want to use this to add the URLs:

```
fruits <- c("Apple", "Orange")
paste(fruits, "juice", sep = "")

contribs <- c("maxheld83", "foobar")
paste0("[@", contribs, "]", "(github.com/", contribs, ")")
```

If `paste()` somehow seems to limiting, there's also the [glue](https://glue.tidyverse.org) package which lets you do a lot more with string interpolation, but that's probably overkill here.

**Comment by samshaffer97** [comment]
i just got this error message in RStudio
>Error in gh::gh("/repos/:owner/:repo/releases", owner = spec_owner(repo_spec),  : 
  GitHub API error (403): 403 Forbidden
  API rate limit exceeded for 131.188.6.22. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
Calls: <Anonymous> ... as_timestamp -> releases -> <Anonymous> -> gh_process_response
Execution halted

not sure how to deal with this

**Comment by maxheld83** [comment]
I think this means that we *did* hit the GitHub API rate limit from your local machine (probably from testing).

The rate limit for local machines can be dramatically increased by providing a GitHub PAT (Personal access token).
You can create it with `usethis::browse_github_pat()` and add it to your `.Renviron file` with `usethis::edit_r_environ()`.

This would then a) go to github.com and generate one of these PATs, b) save them to your (local) `.Renviron`. 
The `.Renviron` is a settings file set sits on your computer, probably a `~`.

The github PAT is bound to your *personal* github account, and it basically just tells GitHub that you're not some bot, but authorized via your personal credentials.

The github rate limit should then be high enough for us to never hit it.

If the same function is used on other computers, they will hit it again, because this is per-device.

May be a problem on the server as well, but we'll worry about that when we get the problem.
Perhaps the Github actions server has a higher rate limit anyway.

Hope this helps.

Docs on this are i https://usethis.r-lib.org/reference/browse_github_token.html

Oh, and the GitHub PAT should be kept safely, naturally.

**Comment by maxheld83** [comment]
the github docs for PATs is here: https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line

the above r function just does this clicking for you
