### ISSUE TITLE
add resources on how to start contributing to open source

### ISSUE THREAD

**Issue by maxheld83** [soztag/fossos#86]
we need some more good articles on this topic.
Please suggest them here.

**Comment by Ch1pzZz** [comment]
https://rubygarage.org/blog/how-contribute-to-open-source-projects

Don´t know if this is "too basic" or at all what you were looking for but this would probably help as an "ease into the topic" article to refer students to when you host the class again!

**Comment by DomBert** [comment]
*Blogs and first information:*

AlgoliaBlog
https://blog.algolia.com/start-your-open-source-career/

First Timers Only
https://www.firsttimersonly.com

First Contributions
https://github.com/firstcontributions/first-contributions

Opensource.com
https://opensource.com/article/18/3/First-Contributions-project

How to get started with Open Source
https://www.hackerearth.com/getstarted-opensource/

*Pages to start actively:*

Up for Grabs
https://up-for-grabs.net/#/

CodeTriage
https://www.codetriage.com/what

**Comment by maxheld83** [comment]
closed #162
