### ISSUE TITLE
sign up to RStudio community and post your profile here

### ISSUE THREAD

**Issue by maxheld83** [soztag/fossos#9]

**Comment by Mococoa22** [comment]
my username is moco
(https://community.rstudio.com/u/moco/activity)

**Comment by samshaffer97** [comment]
https://community.rstudio.com/u/samshaffer97/activity

**Comment by mkkkt** [comment]
https://community.rstudio.com/u/mkkkt/activity
my username is mkkkt.

**Comment by t-rop** [comment]
This is my RStudio profile: https://community.rstudio.com/u/t-rop/activity

**Comment by maxheld83** [comment]
thanks to everyone, who signed up already.
It'd be great if you could also spruce up the profiles a little bit, maybe a sentence or so who you are, and a picture.
If you don't want to use *your* picture, feel free to use some other image (as @Mococoa22 did).
Should be the same pictures as here on the github profile.

The idea is that these profiles are looking a little friendly and personal. (community.rstudio.com especially is a really friendly place).

**Comment by Elen93** [comment]
Here is my profile
https://community.rstudio.com/u/Elssa/activity

**Comment by DomBert** [comment]
This is my RStudio profile: https://community.rstudio.com/u/dombert/activity 
Right now, it's just functional, but I will color it up those days!

**Comment by KonsWeb** [comment]
My profile's here: https://community.rstudio.com/u/KonsWeb/activity

**Comment by maxheld83** [comment]
7/14

**Comment by spaniel19** [comment]
My not so pretty profile! 

https://community.rstudio.com/u/spaniel19/activity

**Comment by AndreM92** [comment]
My Rstudio community profile
https://community.rstudio.com/u/AndreM92/summary
